# Именно это имя показывается везде
# Ctrl + Space = Помощник кода
name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

# Каждый джоб запускается в отдельном контейнере
jobs:
  JobStart:
    runs-on: ubuntu-latest
    steps:
    - name: Print Jo Started
      run: echo "Job Started"
  build:
    # те самые раннеры
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11 (1 Step)
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven (2 Step)
      run: mvn -B package --file pom.xml
      
  JobEnd:
    runs-on: ubuntu-latest
    steps:
    - name: Print Job Finished
      run: echo "Job Finished"
