# Иду по уроку https://www.youtube.com/watch?v=Yg5rpke79X4
# Именно это имя показывается везде
# Ctrl + Space = Помощник кода
name: Java CI with Maven
# Глобальные энв варс, доступные всем джобам
env:
  APPLICATION_NAME: "MAVEN"
  # втавляем номер коммита в переменную 
  DEPLOY_PACKAGE_NAME: "myapp.java-version-${{ github.sha }}"

on: pull_request

# Каждый джоб запускается в отдельном контейнере и ПАРАЛЛЕЛЬНО с другими
jobs:
  JobStart:
    runs-on: ubuntu-latest
    steps:
    - name: Print Job Started
      run: echo "Job Started"
    - name: Print Application Name
      run: |
        echo "Application Name: ${{ env.APPLICATION_NAME }}"
    - name: Clone My repo to work dir #Всегда используется
      uses: actions/checkout@v1
    - name: List current directory
      run: ls -lha
      
  build:
    # те самые раннеры
    runs-on: ubuntu-latest
    # переменные только для джобы
    env:
      VAR1: "MAVEN"
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11 (1 Step)
      # Переменная только для этого степа
      env:
        VAR1: "MAVEN"
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven (2 Step)
      run: mvn -B package --file pom.xml
      
  JobEnd:
    runs-on: ubuntu-latest
    # Запустится не параллельно а только после джобы build
    needs: [build]
    steps:
    - name: Print Job Finished
      run: |
        echo "Job Finished"
        echo "Deploy package name is ${{ env.DEPLOY_PACKAGE_NAME }}"
        
  test_with_actions_from_run:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - id: actions
      run: |
        echo "value=$ACTIONS" >> $GITHUB_OUTPUT
      env:
        ACTIONS: |
          [{"label":"Click Me","description":"Click me to get free RAM","identifier":"sent_to_webhook"}]
    - uses: LouisBrunner/checks-action@v1.5.0
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        name: Test With Actions From Run
        conclusion: success
        action_url: https://example.com/action
        # output.summary is required with actions!
        output: |
          {"summary":"Some warnings in README.md"}
        actions: ${{ steps.actions.outputs.value }}
